### ISSUE TITLE
Exception downloading Thread script to file.

### ISSUE THREAD

**Issue by adhambadr** [joltup/react-native-threads#46]
Its not a RN 0.56 problem, rather actually putting the threads file in any Directory other than app root causes this. 

```javascript
const thread = new Thread('./services/contacts.js');
thread.onmessage = (message) => console.log(message);
```

```java
Exception in native call
                              java.lang.RuntimeException: Exception downloading thread script to file
                                                                               at com.reactlibrary.RNThreadModule.downloadScriptToFileSync(RNThreadModule.java:220)
                                                                               at com.reactlibrary.RNThreadModule.createDevBundleLoader(RNThreadModule.java:175)
                                                                               at com.reactlibrary.RNThreadModule.startThread(RNThreadModule.java:68)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                               at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
                                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
                                                                               at java.lang.Thread.run(Thread.java:761)
                                                                            Caused by: java.io.FileNotFoundException: /data/user/0/com.testproject/files/services/contacts (No such file or directory)
                                                                               at java.io.FileOutputStream.open(Native Method)
                                                                               at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
                                                                               at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
                                                                               at okio.Okio.sink(Okio.java:181)
                                                                               at com.reactlibrary.RNThreadModule.downloadScriptToFileSync(RNThreadModule.java:217)
                                                                               at com.reactlibrary.RNThreadModule.createDevBundleLoader(RNThreadModule.java:175) 
                                                                               at com.reactlibrary.RNThreadModule.startThread(RNThreadModule.java:68) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
                                                                               at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160) 
                                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                               at android.os.Handler.handleCallback(Handler.java:751) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
                                                                               at java.lang.Thread.run(Thread.java:761) ```

**Comment by tanmaybhatt** [comment]
Any solutions to this? I am also having this issue.

**Comment by gitTeub** [comment]
I also have this issue

**Comment by patrickCode** [comment]
Any update on this issue? I am facing the same thing.

**Comment by Traviskn** [comment]
Actually, I am able to reproduce this in a new app - I wonder why it wasn't breaking an existing app I have with the thread files in nested directories. Looking into it now to see if I can figure out what's going wrong

**Comment by adhambadr** [comment]
@Traviskn yeah it happens in Dev didn't try it yet in production. My solution was to simply "bundle" everything in the root of the app as "worker.threads.js" just as your exampleand that file imports the stuff needed from other folders, that works now. 
I tried to debug the native code to help out but couldn't really reflect any changes as there was no clear "build" process documented, contrary to other native modules changing the Java files in my node_modules folder didn't have any effect as I believe you pre-built the classes. But my guess would be something in these lines : 
```
JSBundleLoader bundleLoader = getDevSupportManager().getDevSupportEnabled()
            ? createDevBundleLoader(jsFileName, jsFileSlug)
            : createReleaseBundleLoader(jsFileName, jsFileSlug);
```
that the ```getDevSupportManager```falsely recognises it as in production mode.
